### ISSUE TITLE
Changes to be made in the HLCEES CSL Styles

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/bibliography#12]
@abausi @FrancescaPanini @eu-genia have developed the following list of corrections to be made to the styles. 
This need to be tested, eventually implemented and submitted to the CSL style repository.

- [x] 	Long names and short names styles need to be aligned, at the moment there seem to be some discrepancies (even though I haven’t experienced it myself).
- [x] 	When the same person is author and editor/translator the name does not need to be repeated.

Basset, R. 1916. Le synaxaire arabe jacobite (rédaction copte), III: Mois de Toubeh et d’Amschir, ed., tr. R. Basset, Patrologia Orientalis, 11/5 (Paris: Firmin-Didot et Cie, 1916).
>
Basset, R. 1916. Le synaxaire arabe jacobite (rédaction copte), III: Mois de Toubeh et d’Amschir, ed., tr., Patrologia Orientalis, 11/5 (Paris: Firmin-Didot et Cie, 1916).

- [x] In both English (UK and US) and German, the style for the short references puts the abbreviations “p.”, “pp.” or “S.” before the page number(s):

Bausi 2002, S. 12
>
Bausi 2002, 12

- [x] 	In the style for German, the abbreviation “hrsg.” is written small, while is should be written with capital letter, i.e. “Hrsg.”

- [x]	In the style for thesis, there is a missing comma:
Hummel, S. 2020. Das hagiografische Werk zu Śarṣ́a Ṗeṭros. Werkgenese und Teiledition Doktorarbeit, Universität Hamburg (2020).
>
Hummel, S. 2020. Das hagiografische Werk zu Śarṣ́a Ṗeṭros. Werkgenese und Teiledition, Doktorarbeit, Universität Hamburg (2020).

- [x]	In the style for manuscript, there is a missing comma:

Bausi, A. 2019. The Ethiopian Biblical Canon in its earliest literary attestation: An assessment of the evidence Paper presented at the Society of Biblical Literature Annual Meeting 2019, 23–26 November 2019 (San Diego, CA: 2019).
>
Bausi, A. 2019. The Ethiopian Biblical Canon in its earliest literary attestation: An assessment of the evidence, Paper presented at the Society of Biblical Literature Annual Meeting 2019, 23–26 November 2019 (San Diego, CA: 2019).

- [x]	There is the following problem with the syntax for reprint and later editions of a work: 

Taddesse Tamrat 2009. Church and State in Ethiopia: 1270–1527, (repr.) (Los Angeles, CA: Tsehai Publishers, 2009).
>
Taddesse Tamrat 2009. Church and State in Ethiopia: 1270–1527, repr. (Los Angeles, CA: Tsehai Publishers, 2009).

Beachy, M. 2018. A Brief Grammar of Dizin, (2nd edn) (Mizan Teferi: The Bench Maji Zone–SIL Ethiopia, 2018).
>
Beachy, M. 2018. A Brief Grammar of Dizin, 2nd edn (Mizan Teferi: The Bench Maji Zone–SIL Ethiopia, 2018).

- [x]	Is there a way to express authorial and editorial collaborations as follows:

Secondary authors:

Gori, A., A. Regourd, J. R. Brown, and S. Delamarter 2014. A Handlist of the Manuscripts in the Institute of Ethiopian Studies, II: The Arabic Materials of the Ethiopian Islamic Tradition, Ethiopic Manuscripts, Texts, and Studies, 20 (Eugene, OR: Pickwick Publications, 2014).
>
Gori, A. 2014. A Handlist of the Manuscripts in the Institute of Ethiopian Studies, II: The Arabic Materials of the Ethiopian Islamic Tradition, with contributions from A. Regourd, J. R. Brown, and S. Delamarter, Ethiopic Manuscripts, Texts, and Studies, 20 (Eugene, OR: Pickwick Publications, 2014).

Assistant editors:

Bausi, A. and E. Sokolinski 2016. 150 Years after Dillmann’s Lexicon: Perspectives and Challenges of Gǝʿǝz Studies, eds A. Bausi and E. Sokolinski, Supplement to Aethiopica, 5 (Wiesbaden: Harrassowitz Verlag, 2016).
>
Bausi, A. 2016. 150 Years after Dillmann’s Lexicon: Perspectives and Challenges of Gǝʿǝz Studies, ed., with assistance from E. Sokolinski, Supplement to Aethiopica, 5 (Wiesbaden: Harrassowitz Verlag, 2016).

An additional problem comes from the fact that sometimes there is a collaboration among editors, no assistance:

EAe. S. Uhlig, ed., Encyclopaedia Aethiopica, I: A–C; II: D–Ha; III: He–N; in cooperation with A. Bausi, ed., IV: O–X; A. Bausi in cooperation with S. Uhlig, ed., V: Y–Z. Supplementa. Addenda et Corrigenda. Maps. Index (Wiesbaden: Harrassowitz Verlag, 2003, 2005, 2007, 2010, 2014).

Do you think there is any solution to this?

- [x]	We still have the problems with the publication date which we had tried to overcome with the ‘bibliography tool’. Since a few years have gone by, can we look into this gain to see if there is now a better solution available?

- [x]	One more point is the fact that encyclopaedia entries (which we as a rule do not give in the final bibliography) are not distinguished by the additional letter (2010a etc.), so that more entries by the same author have the same abbreviated form, e.g. Liuzzo 2020, Liuzzo 2020 etc.; in fact, they are not counted, and this generates confusion, among them, and also with other non-encyclopaedic contribution of the same year; it is (also) one of the reasons why we do not quote encyclopaedic entries in the final bibliography. Can we understand why this happens and fix this too?

- [x]	The volume number is not ordered correctly in editions and translations: it must follow the title, not the ed, tr.,
Conti Rossini, C. and L. Ricci 1964. Il libro della luce del negus Zarʾa Yāʿqob (Maṣḥafa Berhān), eds C. Conti Rossini and L. Ricci, I, Corpus Scriptorum Christianorum Orientalium, 250, Scriptores Aethiopici, 47 (Louvain: Secrétariat du CorpusSCO, 1964).
>
Conti Rossini, C. and L. Ricci 1964. Il libro della luce del negus Zarʾa Yāʿqob (Maṣḥafa Berhān), I, eds, Corpus Scriptorum Christianorum Orientalium, 250, Scriptores Aethiopici, 47 (Louvain: Secrétariat du CorpusSCO, 1964).

- [x]	The format for newspaper articles does not match out style:
Steinman, D. 2017. ‘Ethiopia’s Cruel Con Game’, Forbes, 3 March 2017.
>
Steinman, D. 2017. ‘Ethiopia’s Cruel Con Game’, Forbes (3 March 2017).

**Comment by abausi** [comment]
I fully agree!

Il 16.09.2021 09:07, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment]
I have made here a collection of entries used as examples for testing.
https://www.zotero.org/pietroliuzzo/collections/XVTZQJ6P
it is in my personal and public library, you should be able to see what is in it.

**Comment by PietroLiuzzo** [comment]
For the first point, I cannot see any discrepancies in the test set besides the intended ones.
If you want to reproduce the test:
I have called the printed bibliography for the collection for each style

- https://api.zotero.org/users/1405276/collections/XVTZQJ6P/items?format=bib&locale=en-GB&style=hiob-ludolf-centre-for-ethiopian-studies
- https://api.zotero.org/users/1405276/collections/XVTZQJ6P/items?format=bib&locale=en-GB&style=hiob-ludolf-centre-for-ethiopian-studies-with-url-doi
- https://api.zotero.org/users/1405276/collections/XVTZQJ6P/items?format=bib&locale=en-GB&style=hiob-ludolf-centre-for-ethiopian-studies-long-names

I have downloaded the HTML output for each
I cleaned the HTML to make it valid XML (closed open meta element)
I have run diff files from the oxygen package both three- and two-ways comparisons with inline and XML algorithms ignoring white spaces.

My results are that 
- The only difference in the output between base and long-names are the long names. 
- The only difference between base and with-doi, is the added DOI. 

I think this is what is to be expected. If you have examples of the discrepancies I can look at them.

**Comment by PietroLiuzzo** [comment]
The second point was not solvable for me. I tried several workarounds. I have posted to the Zotero forum for illumination.
https://forums.zotero.org/discussion/91817/omit-name-if-author-is-same-as-editor-and-translator#latest
removing  `      <label variable="locator" form="short"/> ` from the `macro[@name='citation-locator']` removes p. and **any other** prefix from the cited range. This affects only the style, so, not the website, which does not use the style for the rendering of citedRange

**Comment by PietroLiuzzo** [comment]
big H (and Ü for übers.) replaced

**Comment by PietroLiuzzo** [comment]
the fix for the comma has been implemented adding a further elseif in the macro[@name='text'] with a `@suffix=","`

```
<else-if type="bill book graphic legal_case legislation manuscript motion_picture report song speech webpage" match="any">
        <text variable="title" font-style="italic"/>
      </else-if>
      <else-if type="thesis" match="any">
        <text variable="title" font-style="italic" suffix=","/>
      </else-if>
```

**Comment by PietroLiuzzo** [comment]
further update of the same as above for the following point
````
<else-if type="bill book graphic legal_case legislation motion_picture report song speech webpage" match="any">
        <text variable="title" font-style="italic"/>
      </else-if>
      <else-if type="thesis manuscript" match="any">
        <text variable="title" font-style="italic" suffix=","/>
      </else-if>
````

**Comment by PietroLiuzzo** [comment]
the brackets around the edition have been removed by modifying the macro[@name='locator']
```
      <else-if type="bill book chapter graphic legal_case legislation motion_picture paper-conference report song" match="any">
        <group prefix=" " suffix="" delimiter=", ">
          <text macro="edition"/>
        </group>
      </else-if>
```

**Comment by PietroLiuzzo** [comment]
for the editorial/authorial collaborations/contributions etc. After some exploration with types and styles, I think there is no satisfactory workaround.
- if the role is changed from author to collaborator, the collaborator is omitted as it is considered a non-bibliographical information and is not mapped to any variable in CSL.
- in the Zotero forums a similar question has been answered proposing to type in with the author name "with the collaboration of Surname" which I think makes the data very dirty for no clear reason.
- the same workaround within title will turn out in the right sequence but italicized and has the same issue as above.
- if the data has to be made dirty then I would go for volume instead of author or title. you would enter there the formatted string "with contributions from A. Regourd, J. R. Brown, and S. Delamarter" and switch the role to collaborator if listed among the authors. 
The examples above will result as follows:
<img width="1573" alt="Bildschirmfoto 2021-09-17 um 08 09 08" src="https://user-images.githubusercontent.com/508012/133733089-6062d65c-3519-455e-ac16-926ad25096eb.png">

I think there is no such solution for the EAe general bibliographic reference.  Perhaps add a note in the bibliographic record in Zotero with this formatted notation, saying that this is the recommended way to detail this.

**Comment by PietroLiuzzo** [comment]
I am not sure which date problem is referred to. I checked the zotero forums for the ranges issue and I could not find  relevant updates. the Issued: 1999/2000 method in Extra is still the suggested way to work with ranges.
 question posted to the Zotero blog
https://forums.zotero.org/discussion/91829/dates-in-other-calendars?new=1

**Comment by PietroLiuzzo** [comment]
In my understanding the letters are assigned after the bibliography is composed, as it makes sense, because they are context specific. Their function is to disambiguate citations which would be the same. Since the way in which we use citation is already disambiguated because the EAe entries are cited in a different way, there is no need to further disambiguate them. It is inconsistent that, in a situation in which these are included in the list of references, they are with a format which is similar to to the others and thus creates confusion.
for example we have the following
<img width="1570" alt="Bildschirmfoto 2021-09-17 um 09 26 59" src="https://user-images.githubusercontent.com/508012/133743003-0b8bf072-ce15-42b8-a153-bf99fcb5086b.png">

to be consistent with the citations and still have this in the bibliography, we could avoid producing a different reference structure
<img width="1563" alt="Bildschirmfoto 2021-09-17 um 09 32 34" src="https://user-images.githubusercontent.com/508012/133742971-ceda2bcc-3b98-4d69-aced-6ba2f59a860b.png">

The sorting by date would be preserved but the apparently mistaken (in facts entirely correct) letters would not be present in favour of a consistent representation of the citation used in the text.

Or, for the sake of standalone bibliographies where citations are not used in the text we could avoid disambiguating the citation of the encyclopaedia.
<img width="1569" alt="Bildschirmfoto 2021-09-17 um 09 41 14" src="https://user-images.githubusercontent.com/508012/133744421-c6469404-90d3-4212-853c-eff0f06715a0.png">

This could simply be a modified style which can be shared locally and used by those who need it for specific purposes, I would not push it to the CSL repository. the modification is minimal, i.e. removing the choose element from citation.

**Comment by PietroLiuzzo** [comment]
moving the block
````
 <choose>
              <if type="article article-journal article-magazine article-newspaper" match="any">
                <text value=","/>
              </if>
              <else-if type="paper-conference" match="any">
                <group prefix=", ">
                  <number variable="volume"/>
                </group>
              </else-if>
              <else>
                <group prefix=", ">
                  <number variable="volume" form="ordinal"/>
                </group>
              </else>
            </choose> 
````
into the group with *-contributors anticipates the volume

Conti Rossini, C. and L. Ricci 1964. Il libro della luce del negus Zarʾa Yāʿqob (Maṣḥafa Berhān), I, eds C. Conti Rossini and L. Ricci, Corpus Scriptorum Christianorum Orientalium, 250, Scriptores Aethiopici, 47 (Louvain: Secrétariat du CorpusSCO, 1964).
Conti Rossini, C. and L. Ricci 1965a. Il libro della luce del negus Zarʾa Yāʿqob (Maṣḥafa Berhān), II, eds, trans. C. Conti Rossini and L. Ricci, Corpus Scriptorum Christianorum Orientalium, 261, Scriptores Aethiopici, 51 (Louvain: Secrétariat du CorpusSCO, 1965).
Conti Rossini, C. and L. Ricci 1965b. Il libro della luce del negus Zarʾa Yāʿqob (Maṣḥafa Berhān), I, tr. C. Conti Rossini and L. Ricci, Corpus Scriptorum Christianorum Orientalium, 251, Scriptores Aethiopici, 48 (Louvain: Secrétariat du CorpusSCO, 1965).
Conti Rossini, C. and L. Ricci 1965c. Il libro della luce del negus Zarʾa Yāʿqob (Maṣḥafa Berhān), II, tr. C. Conti Rossini and L. Ricci, Corpus Scriptorum Christianorum Orientalium, 262, Scriptores Aethiopici, 52 (Louvain: Secrétariat du CorpusSCO, 1965).

**Comment by PietroLiuzzo** [comment]
split up in the macro[@name='locator'] the rendering of the date for article-newspaper
````
<else-if type="article-magazine" match="any">
        <group delimiter="/">
          <text variable="volume"/>
          <text variable="issue"/>
        </group>
        <date form="text" date-parts="year-month-day" variable="issued"/>
      </else-if>
<else-if type="article-newspaper" match="any">
        <group delimiter="/">
          <text variable="volume"/>
          <text variable="issue"/>
        </group>
        <date form="text" date-parts="year-month-day" variable="issued" prefix="(" suffix=")"/>
      </else-if>
````

**Comment by PietroLiuzzo** [comment]
Here are some steps for you to try and test for regressions with the modified style which I just uploaded to this repository.
This is only the main style, if there are no major issues I will then replicate the changes in the variants with long names and dois and submit those to the style repository. I will then make an additional set of variants for the bibliography with normalized citations. These I will only submit to this repository, not to CSL.

I have seen one regression, which however I think was expected given the text of the guidelines, namely the citation for bm:Anon1983AlMawsu which, will have Anon. and not the title.

To test: 
- Download the style from https://github.com/BetaMasaheft/bibliography/blob/master/hiob-ludolf-centre-for-ethiopian-studies-new.csl and add it to Zotero (double click on the file)
- Download the library https://www.zotero.org/pietroliuzzo/collections/XVTZQJ6P/items/Q476BQZ2/collection and import it into your personal library
- Select all items in the collection
- open preferences -> citation -> style -> Style editor
- select Hiob Ludolf Center of Ethiopian Studies New
- see the results
- let me know here, please

**Comment by PietroLiuzzo** [comment]
@eu-genia @FrancescaPanini @abausi

**Comment by eu-genia** [comment]
![image](https://user-images.githubusercontent.com/17987728/133755652-0c362a29-9971-410a-ba07-c5122142df1d.png)

**Comment by PietroLiuzzo** [comment]
I am not a prophet yet, I need to know where the error comes from. you can try and add it from Zotero instead of double clicking, if that is when the error occurs. preferences->citation->style-> + and select the style

**Comment by abausi** [comment]
I had no problem and could apply the new style, which seems OK in all 
examples I checked

Il 17.09.2021 11:03, Pietro Liuzzo ha scritto:

**Comment by eu-genia** [comment]
it worked now, looks good

**Comment by abausi** [comment]
I noted something to be solved:

if the field "author" is empty, then the title appears in this form:

/Digital Approaches to Ethiopian and Eritrean Studies/ 2019. , 
Supplement to Aethiopica, 8 (2019).

with no repetition of the title, and a hanging comma. What can we do?

Il 17.09.2021 11:44, Eugenia ha scritto:

**Comment by abausi** [comment]
To the test records it should be added such an entry, with no author

Il 17.09.2021 12:47, Alessandro Bausi ha scritto:

**Comment by PietroLiuzzo** [comment]
I have added a variant to the volume options to avoid this behaviour.

**Comment by PietroLiuzzo** [comment]
will wait further feedback before uploading a new version including this correction

**Comment by PietroLiuzzo** [comment]
there was an entry with no author, but the current guidelines dictate not to have such records, where they say 

> "If the name of the authors is not given and not known, use Anon." 

which is the same point I raised above, which generates the citation with Anon. and not with the title as previously.

**Comment by PietroLiuzzo** [comment]
@FrancescaPanini

**Comment by FrancescaPanini** [comment]
Hi,
I looked at the test cases and I think the new style reaches a nice result in a few problematic areas. 

l found some mistakes in the output that I am listing here hoping that they help in the discussion and final result. I skimmed throught the conversation, so apologies I am noting something it was already dealt with:
<img width="619" alt="screenshot test" src="https://user-images.githubusercontent.com/20635711/134306420-c9f3c066-e7d1-438b-b939-bc57824090e9.PNG">

**Comment by abausi** [comment]
the first has to do with the "Anon." issue; there must be always an author;

(in Basset the volume should be: ", III:", but it is not the point here;)

I am not sure about "n.p." etc. but Francesca knows better;

I agree on Steiman.


Il 22.09.2021 10:08, FrancescaPanini ha scritto:

**Comment by PietroLiuzzo** [comment]
Thanks for the feedback.
- the first case is a feature of Style processor. Since in this case title is used as substitute for the author, the title is not printed in its place to [avoid duplication](https://docs.citationstyles.org/en/stable/specification.html#substitute). Actually this record is wrong according to the guidelines and should use Anon. the result is like follows.  
 Anon. 1983. _Al-Mawsūʿa al-fiqhiyya_, I–XLV (Kuwait: Wizārat al-Awqāf wa-l-šuʾūn al-islāmiyya, 1983).
- As specified above, I am awaiting for illumination about this. I do not think that it is solvable.
- I never noticed that behaviour! I am not able to reproduce it though in the CSL, sorry. I did try with macros and text[@value] but it does not seem to be an option...
- I removed that comma in the last case.

**Comment by PietroLiuzzo** [comment]
I have added to the repository the update new style and the updated variants 
- long names
- doi
- a new variant which avoids the special citation format for Encyclopaedia entries as discussed above.

I will now propose this changes to the central repository, but you can already install the new styles from our repository.

**Comment by PietroLiuzzo** [comment]
the official styles have been updated.
