### ISSUE TITLE
Creating bm: "marqueurs" in Zotero EthioStudies

### ISSUE THREAD

**Issue by anaiswion** [BetaMasaheft/bibliography#8]
Hello everybody. I've been trying to create some new bm: "marqueurs" (this is the name in my French Zotero browser). And it works ! But I'd like to be sure to do it the right way. 
Check please the 2 following references : 
- Wright, 1870, Catalogue Magdala
- Beckingham and Huntingford, 1961, Prester John. 

Thanks.

**Comment by PietroLiuzzo** [comment]
mmmm... do you have editing rights in the Ethio-Studies library? this would suprise me. Are you sure that you are adding the tags in the group library?

**Comment by PietroLiuzzo** [comment]
please send direct links to the entries so that we can check more quickly.

**Comment by PietroLiuzzo** [comment]
e.g. if I look here
https://www.zotero.org/groups/358366/ethiostudies/search/magdala%20wright/titleCreatorYear/items/QH3MIP4S/item-list
a tag is already present and you do not need to add any.
This page is your reference for the use of Zotero and tags
https://betamasaheft.eu/Guidelines/?id=zotero

**Comment by anaiswion** [comment]
I don't know actually, that's also why I am asking :-) ! I can see the bm: tag I've been adding to Wright 1870 a few days ago in my Zotero browser even after I refresh it. So I guess it's here. 

If you search for bm:Wright1870Magdala can you find it ?

**Comment by anaiswion** [comment]
OK so the answer is yes. I've been adding this tag last week. And a few minutes ago I've been adding this one

bm:BeckHunt1961PresterJohn

**Comment by PietroLiuzzo** [comment]
In whatever Zotero interface you are using, make sure you are looking at the record in the Ethio-Studies group library. this is listed in the right, both online and locally. 

The tags are there. you are all set.

Please stick to the guidelines linked above, and strictly avoid removing or altering existing tags. These may have been used already in many instances and become incorrect for no reason. the tag in itself is simply an handle and correcting it to match a format is entirely unnecessary.
you can check the use of the tag in the reverse index.

https://betamasaheft.eu/bibliography
