### ISSUE TITLE
Zotero EthioStudies : ref missing

### ISSUE THREAD

**Issue by anaiswion** [BetaMasaheft/bibliography#9]
Could it be possible to add the following reference to the bibliography : 

Monneret de Villard, Ugo, "Aksum : Ricerche di topografia generale", Pontificium institutum biblicum, Roma, 1938. 

And add to it a bm: tag ? 

I would be ok to do it of course but I'm not sure I have the right to do it. 

I am assigning Pietro "by default" but please do not hesitate to remind me who is in charge of this Zotero if necessary. 

Thanks !

**Comment by PietroLiuzzo** [comment]
Eugenia can do it in a much more precise and better way than I will ever do!

**Comment by eu-genia** [comment]
sure, done, bm:Monneret1938Aksum
